apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.stack.appsody.dev/author: Harish Yayi <yharish991@gmail.com>
    commit.stack.appsody.dev/committer: GitHub <noreply@github.com>
    commit.stack.appsody.dev/contextDir: /incubator/java-spring-boot2
    commit.stack.appsody.dev/date: Fri Feb 21 16:00:55 2020 +0000
    commit.stack.appsody.dev/message: java-spring-boot2 - add additional stack maintainers
      to the stack (#681)
    image.opencontainers.org/created: "2020-02-25T22:50:26-05:00"
    stack.appsody.dev/authors: Erin Schnabel <schnabel@us.ibm.com>, Ozzy Osborne <ozzy@ca.ibm.com>,
      Richard Trotter <rtrotter@us.ibm.com>, Harish Yayi <hyayi@us.ibm.com>
    stack.appsody.dev/configured: docker.io/appsody/java-spring-boot2:0.3
    stack.appsody.dev/created: "2020-02-21T16:05:31Z"
    stack.appsody.dev/description: Spring Boot using OpenJ9 and Maven
    stack.appsody.dev/documentation: https://github.com/appsody/stacks/tree/master/incubator/java-spring-boot2/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 04f9230fac0d9add6c367c10e9908192fedcd7cc
    stack.appsody.dev/source: https://github.com/appsody/stacks/tree/master/incubator/java-spring-boot2/image
    stack.appsody.dev/tag: docker.io/appsody/java-spring-boot2:0.3.26
    stack.appsody.dev/title: Spring Boot®
    stack.appsody.dev/url: https://github.com/appsody/stacks/tree/master/incubator/java-spring-boot2
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: sample-service-binding-db2
    stack.appsody.dev/id: java-spring-boot2
    stack.appsody.dev/version: 0.3.26
  name: sample-service-binding-db2
spec:
  applicationImage: harishyayi/sample-service-binding-db2:0368
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    endpoints:
    - path: /actuator/prometheus
    labels:
      k8s-app: sample-service-binding-db2
  pullPolicy: Always
  service:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"
    type: NodePort
  stack: java-spring-boot2
  version: 1.0.0
  volumeMounts:
  - mountPath: /etc/secrets/db2
    name: db2-secrets
    readOnly: true
  volumes:
  - name: db2-secrets
    secret:
      secretName: db2-secrets
status: {}
